Language.create!(name: "Ruby")
Language.create!(name: "JavaScript")
Language.create!(name: "HTML")
Language.create!(name: "CSS")
Language.create!(name: "Rails")
Language.create!(name: "Python")
Language.create!(name: "C++")
Language.create!(name: "Java")

Cohort.create!(name: "Elephants")
Cohort.create!(name: "Lizards")
Cohort.create!(name: "Trees")
Cohort.create!(name: "Cats")
Cohort.create!(name: "Llamas")
Cohort.create!(name: "Pies")
Cohort.create!(name: "Ducks")

Phase.create!(name: "Phase One")
Phase.create!(name: "Phase Two")
Phase.create!(name: "Phase Three")
