Language.create!(name: "Ruby")
Language.create!(name: "Sinatra")
Language.create!(name: "Rails")
Language.create!(name: "HTML")
Language.create!(name: "JavaScript")
Language.create!(name: "C")
Language.create!(name: "SQL")
Language.create!(name: "C++")
Language.create!(name: "Python")

Cohort.create!(name: "Gophers")
Cohort.create!(name: "Doves")
Cohort.create!(name: "Eggs")
Cohort.create!(name: "Lions")
Cohort.create!(name: "Tutles")
Cohort.create!(name: "Ducks")
Cohort.create!(name: "Bears")

Phase.create!(name: "Phase One")
Phase.create!(name: "Phase Two")
Phase.create!(name: "Phase Three")
